"""empty message

Revision ID: 656da2cf1770
Revises: 81eac70c57f9
Create Date: 2023-03-01 19:22:23.627393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656da2cf1770'
down_revision = '81eac70c57f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('opening_crawl', sa.String(length=256), nullable=True),
    sa.Column('director', sa.String(length=128), nullable=True),
    sa.Column('producer', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films')
    # ### end Alembic commands ###
